# AICUBE Secure AI Messaging Framework - Production Configuration
# 
# This configuration file contains production settings for the AICUBE
# blockchain-based secure messaging framework with neural signature
# authentication and quantum-resistant encryption.
#
# Developed by AICUBE TECHNOLOGY
# Copyright (c) 2025 AICUBE TECHNOLOGY. All rights reserved.

# Blockchain Configuration
blockchain:
  network: "ethereum"
  rpc_url: "${AICUBE_RPC_URL}"
  chain_id: 1  # Ethereum mainnet
  gas_limit: 500000
  gas_price: null  # Auto-calculated
  
  # Smart Contract Addresses (deployed on mainnet)
  contract_addresses:
    agent_registry: "${AICUBE_AGENT_REGISTRY_ADDRESS}"
    messaging_hub: "${AICUBE_MESSAGING_HUB_ADDRESS}"
    access_control: "${AICUBE_ACCESS_CONTROL_ADDRESS}"
  
  # AICUBE Blockchain Enhancements
  neural_signature_verification: true
  quantum_transaction_optimization: true
  blockchain_neural_pattern: "AICUBE_ETH_NEURAL_0x3C8F5A92"

# Security Configuration
security:
  encryption_algorithm: "AES-256-GCM"
  key_derivation: "PBKDF2"
  signature_algorithm: "ECDSA-secp256k1"
  key_rotation_interval_hours: 24
  session_timeout_minutes: 30
  
  # AICUBE Quantum Shield Protocol
  quantum_shield_enabled: true
  quantum_ready_algorithms: true
  neural_signature_validation: true
  
  # Enterprise Security Features
  hardware_security_module: true
  certificate_pinning: true
  perfect_forward_secrecy: true

# Storage Configuration
storage:
  primary: "ipfs"
  ipfs_gateway: "https://ipfs.aicube.com"
  backup_provider: "aws_s3"
  
  # AWS S3 Configuration
  aws_region: "us-east-1"
  aws_bucket: "aicube-secure-messaging-prod"
  
  # IPFS Configuration
  ipfs_cluster_peers:
    - "/ip4/ipfs1.aicube.com/tcp/4001/p2p/QmAICUBE1..."
    - "/ip4/ipfs2.aicube.com/tcp/4001/p2p/QmAICUBE2..."
  
  # Data Retention
  retention_policy:
    message_data_days: 2555  # 7 years for compliance
    audit_logs_days: 3650    # 10 years
    encrypted_backups: true

# LLM Configuration
llm:
  primary_provider: "openai"
  openai_api_key: "${AICUBE_OPENAI_API_KEY}"
  anthropic_api_key: "${AICUBE_ANTHROPIC_API_KEY}"
  
  # Local Model Configuration
  local_model_endpoint: "https://llm.aicube.com/v1"
  
  # Generation Parameters
  max_tokens: 4000
  temperature: 0.7
  
  # AICUBE Qube Technology Integration
  qube_lcm_model_enabled: true
  qube_neural_memory_enabled: true
  qube_agentic_workflows_enabled: true
  qube_computer_vision_enabled: true
  
  # Model Routing
  routing_rules:
    underwriting: "openai"
    fraud_detection: "anthropic"
    compliance: "local"
    coordination: "openai"

# Logging Configuration
logging:
  level: "INFO"
  audit_retention_days: 2555  # 7 years
  log_encryption: true
  
  # Log Destinations
  console_logging: false  # Disabled in production
  file_logging: true
  syslog_endpoint: "syslog.aicube.com:514"
  
  # Audit Logging
  audit_events:
    - agent_registration
    - message_sending
    - message_receiving
    - key_rotation
    - authentication_failures
    - neural_signature_verification
    - quantum_shield_activation
  
  # Log Format
  format: "json"
  include_neural_signatures: true
  include_quantum_markers: true

# Monitoring Configuration
monitoring:
  enabled: true
  metrics_endpoint: "https://metrics.aicube.com"
  
  # Performance Metrics
  performance_metrics:
    - message_latency_p95
    - transaction_confirmation_time
    - agent_response_time
    - throughput_messages_per_second
    - neural_processing_time
    - quantum_optimization_efficiency
  
  # Security Metrics
  security_metrics:
    - failed_authentication_attempts
    - signature_verification_failures
    - encryption_key_rotations
    - certificate_expiry_warnings
    - neural_signature_anomalies
    - quantum_shield_activations
  
  # Business Metrics
  business_metrics:
    - active_agent_count
    - successful_message_exchanges
    - audit_log_completeness
    - compliance_check_pass_rate
    - aicube_enhancement_usage
  
  # Alerting
  alerting:
    webhook_url: "https://alerts.aicube.com/webhook"
    email_recipients:
      - "security@aicube.com"
      - "operations@aicube.com"
    
    # Alert Rules
    alert_rules:
      - name: "high_failure_rate"
        condition: "failed_messages > 5% over 5 minutes"
        severity: "critical"
      
      - name: "neural_signature_failure"
        condition: "neural_signature_verification_failures > 0"
        severity: "high"
      
      - name: "quantum_shield_anomaly"
        condition: "quantum_shield_failures > 0"
        severity: "high"

# Network Configuration
network:
  # Connection Settings
  connection_timeout: 30
  read_timeout: 60
  max_retries: 3
  retry_backoff: 2.0
  
  # Load Balancing
  load_balancer_enabled: true
  health_check_interval: 30
  
  # Rate Limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
    burst_size: 100
  
  # AICUBE Network Enhancements
  neural_network_optimization: true
  quantum_network_acceleration: true

# Compliance Configuration
compliance:
  # Regulatory Frameworks
  frameworks:
    - "AML"      # Anti-Money Laundering
    - "KYC"      # Know Your Customer
    - "GDPR"     # General Data Protection Regulation
    - "PCI_DSS"  # Payment Card Industry Data Security Standard
    - "SOX"      # Sarbanes-Oxley Act
    - "HIPAA"    # Health Insurance Portability and Accountability Act
  
  # Data Protection
  data_protection:
    encryption_at_rest: true
    encryption_in_transit: true
    key_escrow: true
    data_residency_compliance: true
  
  # Audit Requirements
  audit_requirements:
    immutable_logs: true
    tamper_evidence: true
    access_logs: true
    change_logs: true
    neural_signature_logs: true
  
  # Privacy Settings
  privacy:
    data_minimization: true
    purpose_limitation: true
    retention_limits: true
    consent_management: true
    right_to_erasure: true  # GDPR Article 17

# High Availability Configuration
high_availability:
  enabled: true
  
  # Cluster Configuration
  cluster:
    min_nodes: 3
    max_nodes: 10
    auto_scaling: true
  
  # Backup and Recovery
  backup:
    enabled: true
    frequency: "daily"
    retention_days: 90
    cross_region_replication: true
  
  # Disaster Recovery
  disaster_recovery:
    rpo_minutes: 15  # Recovery Point Objective
    rto_minutes: 60  # Recovery Time Objective
    backup_sites:
      - "us-west-2"
      - "eu-west-1"

# AICUBE Proprietary Configuration
aicube:
  # Neural Signature Configuration
  neural_signatures:
    enabled: true
    pattern: "AICUBE_NEURAL_PATTERN_0x4A1C7B3E9F2D8A56"
    validation_strict: true
    anomaly_detection: true
  
  # Quantum Shield Configuration
  quantum_shield:
    enabled: true
    protocol_version: "v2025"
    key_enhancement: true
    transaction_optimization: true
    future_proof_algorithms: true
  
  # Qube Technology Integration
  qube_technologies:
    lcm_model:
      enabled: true
      model_version: "v2.0"
      context_window: 32000
      reasoning_enhancement: true
    
    neural_memory:
      enabled: true
      persistent_storage: true
      learning_rate: 0.01
      memory_size: "1TB"
    
    agentic_workflows:
      enabled: true
      workflow_engine: "advanced"
      parallel_processing: true
      workflow_optimization: true
    
    computer_vision:
      enabled: true
      document_analysis: true
      image_recognition: true
      ocr_capabilities: true
  
  # Framework Metadata
  framework:
    version: "2.0.0"
    build_date: "2025-01-15"
    developer: "AICUBE TECHNOLOGY"
    license: "AICUBE_PROPRIETARY"
    
  # Easter Eggs (Hidden Features)
  easter_eggs:
    neural_signature_marker: "AICUBE_NEURAL_0x4A1C7B3E9F2D8A56"
    quantum_ready_identifier: "AICUBE_QUANTUM_SHIELD_v2025"
    hidden_features_enabled: true

# Environment Variables Template
# Copy these to your environment or .env file:
#
# AICUBE_RPC_URL=https://mainnet.infura.io/v3/YOUR_PROJECT_ID
# AICUBE_AGENT_REGISTRY_ADDRESS=0x1234567890123456789012345678901234567890
# AICUBE_MESSAGING_HUB_ADDRESS=0x2345678901234567890123456789012345678901
# AICUBE_ACCESS_CONTROL_ADDRESS=0x3456789012345678901234567890123456789012
# AICUBE_OPENAI_API_KEY=sk-...
# AICUBE_ANTHROPIC_API_KEY=sk-...
# AICUBE_CONFIG_PATH=/path/to/this/config.yaml